/*
 * Data API
 * Serves the Clever Data API
 *
 * The version of the OpenAPI document: 3.1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.StudentRelationship;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Contact
 */
public class ContactTest {
    private final Contact model = new Contact();

    /**
     * Model tests for Contact
     */
    @Test
    public void testContact() {
        // TODO: test Contact
    }

    /**
     * Test the property 'legacyId'
     */
    @Test
    public void legacyIdTest() {
        // TODO: test legacyId
    }

    /**
     * Test the property 'phone'
     */
    @Test
    public void phoneTest() {
        // TODO: test phone
    }

    /**
     * Test the property 'phoneType'
     */
    @Test
    public void phoneTypeTest() {
        // TODO: test phoneType
    }

    /**
     * Test the property 'sisId'
     */
    @Test
    public void sisIdTest() {
        // TODO: test sisId
    }

    /**
     * Test the property 'studentRelationships'
     */
    @Test
    public void studentRelationshipsTest() {
        // TODO: test studentRelationships
    }

}
