/*
 * Data API
 * Serves the Clever Data API
 *
 * The version of the OpenAPI document: 3.1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Credentials
 */
public class CredentialsTest {
    private final Credentials model = new Credentials();

    /**
     * Model tests for Credentials
     */
    @Test
    public void testCredentials() {
        // TODO: test Credentials
    }

    /**
     * Test the property 'districtUsername'
     */
    @Test
    public void districtUsernameTest() {
        // TODO: test districtUsername
    }

}
