/*
 * Data API
 * Serves the Clever Data API
 *
 * The version of the OpenAPI document: 3.1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Disability
 */
public class DisabilityTest {
    private final Disability model = new Disability();

    /**
     * Model tests for Disability
     */
    @Test
    public void testDisability() {
        // TODO: test Disability
    }

    /**
     * Test the property 'disabilityCode'
     */
    @Test
    public void disabilityCodeTest() {
        // TODO: test disabilityCode
    }

    /**
     * Test the property 'disabilityStatus'
     */
    @Test
    public void disabilityStatusTest() {
        // TODO: test disabilityStatus
    }

    /**
     * Test the property 'disabilityType'
     */
    @Test
    public void disabilityTypeTest() {
        // TODO: test disabilityType
    }

}
