/*
 * Data API
 * Serves the Clever Data API
 *
 * The version of the OpenAPI document: 3.1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.DistrictContact;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for District
 */
public class DistrictTest {
    private final District model = new District();

    /**
     * Model tests for District
     */
    @Test
    public void testDistrict() {
        // TODO: test District
    }

    /**
     * Test the property 'districtContact'
     */
    @Test
    public void districtContactTest() {
        // TODO: test districtContact
    }

    /**
     * Test the property 'error'
     */
    @Test
    public void errorTest() {
        // TODO: test error
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'lastSync'
     */
    @Test
    public void lastSyncTest() {
        // TODO: test lastSync
    }

    /**
     * Test the property 'launchDate'
     */
    @Test
    public void launchDateTest() {
        // TODO: test launchDate
    }

    /**
     * Test the property 'lmsState'
     */
    @Test
    public void lmsStateTest() {
        // TODO: test lmsState
    }

    /**
     * Test the property 'loginMethods'
     */
    @Test
    public void loginMethodsTest() {
        // TODO: test loginMethods
    }

    /**
     * Test the property 'mdrNumber'
     */
    @Test
    public void mdrNumberTest() {
        // TODO: test mdrNumber
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'ncesId'
     */
    @Test
    public void ncesIdTest() {
        // TODO: test ncesId
    }

    /**
     * Test the property 'pauseEnd'
     */
    @Test
    public void pauseEndTest() {
        // TODO: test pauseEnd
    }

    /**
     * Test the property 'pauseStart'
     */
    @Test
    public void pauseStartTest() {
        // TODO: test pauseStart
    }

    /**
     * Test the property 'portalUrl'
     */
    @Test
    public void portalUrlTest() {
        // TODO: test portalUrl
    }

    /**
     * Test the property 'sisType'
     */
    @Test
    public void sisTypeTest() {
        // TODO: test sisType
    }

    /**
     * Test the property 'state'
     */
    @Test
    public void stateTest() {
        // TODO: test state
    }

}
