/*
 * Data API
 * Serves the Clever Data API
 *
 * The version of the OpenAPI document: 3.1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.Contact;
import com.konfigthis.client.model.DistrictAdmin;
import com.konfigthis.client.model.Staff;
import com.konfigthis.client.model.Student;
import com.konfigthis.client.model.Teacher;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Roles
 */
public class RolesTest {
    private final Roles model = new Roles();

    /**
     * Model tests for Roles
     */
    @Test
    public void testRoles() {
        // TODO: test Roles
    }

    /**
     * Test the property 'contact'
     */
    @Test
    public void contactTest() {
        // TODO: test contact
    }

    /**
     * Test the property 'districtAdmin'
     */
    @Test
    public void districtAdminTest() {
        // TODO: test districtAdmin
    }

    /**
     * Test the property 'staff'
     */
    @Test
    public void staffTest() {
        // TODO: test staff
    }

    /**
     * Test the property 'student'
     */
    @Test
    public void studentTest() {
        // TODO: test student
    }

    /**
     * Test the property 'teacher'
     */
    @Test
    public void teacherTest() {
        // TODO: test teacher
    }

}
