/*
 * Data API
 * Serves the Clever Data API
 *
 * The version of the OpenAPI document: 3.1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Section
 */
public class SectionTest {
    private final Section model = new Section();

    /**
     * Model tests for Section
     */
    @Test
    public void testSection() {
        // TODO: test Section
    }

    /**
     * Test the property 'course'
     */
    @Test
    public void courseTest() {
        // TODO: test course
    }

    /**
     * Test the property 'created'
     */
    @Test
    public void createdTest() {
        // TODO: test created
    }

    /**
     * Test the property 'district'
     */
    @Test
    public void districtTest() {
        // TODO: test district
    }

    /**
     * Test the property 'ext'
     */
    @Test
    public void extTest() {
        // TODO: test ext
    }

    /**
     * Test the property 'grade'
     */
    @Test
    public void gradeTest() {
        // TODO: test grade
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'lastModified'
     */
    @Test
    public void lastModifiedTest() {
        // TODO: test lastModified
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'period'
     */
    @Test
    public void periodTest() {
        // TODO: test period
    }

    /**
     * Test the property 'school'
     */
    @Test
    public void schoolTest() {
        // TODO: test school
    }

    /**
     * Test the property 'sectionNumber'
     */
    @Test
    public void sectionNumberTest() {
        // TODO: test sectionNumber
    }

    /**
     * Test the property 'sisId'
     */
    @Test
    public void sisIdTest() {
        // TODO: test sisId
    }

    /**
     * Test the property 'students'
     */
    @Test
    public void studentsTest() {
        // TODO: test students
    }

    /**
     * Test the property 'subject'
     */
    @Test
    public void subjectTest() {
        // TODO: test subject
    }

    /**
     * Test the property 'teacher'
     */
    @Test
    public void teacherTest() {
        // TODO: test teacher
    }

    /**
     * Test the property 'teachers'
     */
    @Test
    public void teachersTest() {
        // TODO: test teachers
    }

    /**
     * Test the property 'termId'
     */
    @Test
    public void termIdTest() {
        // TODO: test termId
    }

}
