/*
 * Data API
 * Serves the Clever Data API
 *
 * The version of the OpenAPI document: 3.1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.Credentials;
import com.konfigthis.client.model.Disability;
import com.konfigthis.client.model.Location;
import com.konfigthis.client.model.PreferredName;
import com.konfigthis.client.model.SchoolEnrollment;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Student
 */
public class StudentTest {
    private final Student model = new Student();

    /**
     * Model tests for Student
     */
    @Test
    public void testStudent() {
        // TODO: test Student
    }

    /**
     * Test the property 'created'
     */
    @Test
    public void createdTest() {
        // TODO: test created
    }

    /**
     * Test the property 'credentials'
     */
    @Test
    public void credentialsTest() {
        // TODO: test credentials
    }

    /**
     * Test the property 'disability'
     */
    @Test
    public void disabilityTest() {
        // TODO: test disability
    }

    /**
     * Test the property 'dob'
     */
    @Test
    public void dobTest() {
        // TODO: test dob
    }

    /**
     * Test the property 'ellStatus'
     */
    @Test
    public void ellStatusTest() {
        // TODO: test ellStatus
    }

    /**
     * Test the property 'enrollments'
     */
    @Test
    public void enrollmentsTest() {
        // TODO: test enrollments
    }

    /**
     * Test the property 'ext'
     */
    @Test
    public void extTest() {
        // TODO: test ext
    }

    /**
     * Test the property 'frlStatus'
     */
    @Test
    public void frlStatusTest() {
        // TODO: test frlStatus
    }

    /**
     * Test the property 'gender'
     */
    @Test
    public void genderTest() {
        // TODO: test gender
    }

    /**
     * Test the property 'giftedStatus'
     */
    @Test
    public void giftedStatusTest() {
        // TODO: test giftedStatus
    }

    /**
     * Test the property 'grade'
     */
    @Test
    public void gradeTest() {
        // TODO: test grade
    }

    /**
     * Test the property 'graduationYear'
     */
    @Test
    public void graduationYearTest() {
        // TODO: test graduationYear
    }

    /**
     * Test the property 'hispanicEthnicity'
     */
    @Test
    public void hispanicEthnicityTest() {
        // TODO: test hispanicEthnicity
    }

    /**
     * Test the property 'homeLanguage'
     */
    @Test
    public void homeLanguageTest() {
        // TODO: test homeLanguage
    }

    /**
     * Test the property 'homeLanguageCode'
     */
    @Test
    public void homeLanguageCodeTest() {
        // TODO: test homeLanguageCode
    }

    /**
     * Test the property 'iepStatus'
     */
    @Test
    public void iepStatusTest() {
        // TODO: test iepStatus
    }

    /**
     * Test the property 'lastModified'
     */
    @Test
    public void lastModifiedTest() {
        // TODO: test lastModified
    }

    /**
     * Test the property 'legacyId'
     */
    @Test
    public void legacyIdTest() {
        // TODO: test legacyId
    }

    /**
     * Test the property 'location'
     */
    @Test
    public void locationTest() {
        // TODO: test location
    }

    /**
     * Test the property 'preferredName'
     */
    @Test
    public void preferredNameTest() {
        // TODO: test preferredName
    }

    /**
     * Test the property 'race'
     */
    @Test
    public void raceTest() {
        // TODO: test race
    }

    /**
     * Test the property 'school'
     */
    @Test
    public void schoolTest() {
        // TODO: test school
    }

    /**
     * Test the property 'schools'
     */
    @Test
    public void schoolsTest() {
        // TODO: test schools
    }

    /**
     * Test the property 'section504Status'
     */
    @Test
    public void section504StatusTest() {
        // TODO: test section504Status
    }

    /**
     * Test the property 'sisId'
     */
    @Test
    public void sisIdTest() {
        // TODO: test sisId
    }

    /**
     * Test the property 'stateId'
     */
    @Test
    public void stateIdTest() {
        // TODO: test stateId
    }

    /**
     * Test the property 'studentNumber'
     */
    @Test
    public void studentNumberTest() {
        // TODO: test studentNumber
    }

}
