/*
 * Data API
 * Serves the Clever Data API
 *
 * The version of the OpenAPI document: 3.1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for StudentRelationship
 */
public class StudentRelationshipTest {
    private final StudentRelationship model = new StudentRelationship();

    /**
     * Model tests for StudentRelationship
     */
    @Test
    public void testStudentRelationship() {
        // TODO: test StudentRelationship
    }

    /**
     * Test the property 'relationship'
     */
    @Test
    public void relationshipTest() {
        // TODO: test relationship
    }

    /**
     * Test the property 'student'
     */
    @Test
    public void studentTest() {
        // TODO: test student
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

}
