/*
 * Data API
 * Serves the Clever Data API
 *
 * The version of the OpenAPI document: 3.1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.Credentials;
import com.konfigthis.client.model.Name;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Teacher
 */
public class TeacherTest {
    private final Teacher model = new Teacher();

    /**
     * Model tests for Teacher
     */
    @Test
    public void testTeacher() {
        // TODO: test Teacher
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'created'
     */
    @Test
    public void createdTest() {
        // TODO: test created
    }

    /**
     * Test the property 'credentials'
     */
    @Test
    public void credentialsTest() {
        // TODO: test credentials
    }

    /**
     * Test the property 'district'
     */
    @Test
    public void districtTest() {
        // TODO: test district
    }

    /**
     * Test the property 'ext'
     */
    @Test
    public void extTest() {
        // TODO: test ext
    }

    /**
     * Test the property 'lastModified'
     */
    @Test
    public void lastModifiedTest() {
        // TODO: test lastModified
    }

    /**
     * Test the property 'legacyId'
     */
    @Test
    public void legacyIdTest() {
        // TODO: test legacyId
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'school'
     */
    @Test
    public void schoolTest() {
        // TODO: test school
    }

    /**
     * Test the property 'schools'
     */
    @Test
    public void schoolsTest() {
        // TODO: test schools
    }

    /**
     * Test the property 'sisId'
     */
    @Test
    public void sisIdTest() {
        // TODO: test sisId
    }

    /**
     * Test the property 'stateId'
     */
    @Test
    public void stateIdTest() {
        // TODO: test stateId
    }

    /**
     * Test the property 'teacherNumber'
     */
    @Test
    public void teacherNumberTest() {
        // TODO: test teacherNumber
    }

}
