/*
 * Data API
 * Serves the Clever Data API
 *
 * The version of the OpenAPI document: 3.1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * Section
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class Section {
  public static final String SERIALIZED_NAME_COURSE = "course";
  @SerializedName(SERIALIZED_NAME_COURSE)
  private String course;

  public static final String SERIALIZED_NAME_CREATED = "created";
  @SerializedName(SERIALIZED_NAME_CREATED)
  private String created;

  public static final String SERIALIZED_NAME_DISTRICT = "district";
  @SerializedName(SERIALIZED_NAME_DISTRICT)
  private String district;

  public static final String SERIALIZED_NAME_EXT = "ext";
  @SerializedName(SERIALIZED_NAME_EXT)
  private Object ext;

  /**
   * Gets or Sets grade
   */
  @JsonAdapter(GradeEnum.Adapter.class)
 public enum GradeEnum {
    INFANTTODDLER("InfantToddler"),
    
    PRESCHOOL("Preschool"),
    
    PREKINDERGARTEN("PreKindergarten"),
    
    TRANSITIONALKINDERGARTEN("TransitionalKindergarten"),
    
    KINDERGARTEN("Kindergarten"),
    
    _1("1"),
    
    _2("2"),
    
    _3("3"),
    
    _4("4"),
    
    _5("5"),
    
    _6("6"),
    
    _7("7"),
    
    _8("8"),
    
    _9("9"),
    
    _10("10"),
    
    _11("11"),
    
    _12("12"),
    
    _13("13"),
    
    POSTGRADUATE("PostGraduate"),
    
    UNGRADED("Ungraded"),
    
    OTHER("Other"),
    
    EMPTY("");

    private String value;

    GradeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static GradeEnum fromValue(String value) {
      for (GradeEnum b : GradeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<GradeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final GradeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public GradeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return GradeEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_GRADE = "grade";
  @SerializedName(SERIALIZED_NAME_GRADE)
  private GradeEnum grade;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_LAST_MODIFIED = "last_modified";
  @SerializedName(SERIALIZED_NAME_LAST_MODIFIED)
  private String lastModified;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_PERIOD = "period";
  @SerializedName(SERIALIZED_NAME_PERIOD)
  private String period;

  public static final String SERIALIZED_NAME_SCHOOL = "school";
  @SerializedName(SERIALIZED_NAME_SCHOOL)
  private String school;

  public static final String SERIALIZED_NAME_SECTION_NUMBER = "section_number";
  @SerializedName(SERIALIZED_NAME_SECTION_NUMBER)
  private String sectionNumber;

  public static final String SERIALIZED_NAME_SIS_ID = "sis_id";
  @SerializedName(SERIALIZED_NAME_SIS_ID)
  private String sisId;

  public static final String SERIALIZED_NAME_STUDENTS = "students";
  @SerializedName(SERIALIZED_NAME_STUDENTS)
  private List<String> students = null;

  /**
   * Gets or Sets subject
   */
  @JsonAdapter(SubjectEnum.Adapter.class)
 public enum SubjectEnum {
    ENGLISH_LANGUAGE_ARTS("english/language arts"),
    
    MATH("math"),
    
    SCIENCE("science"),
    
    SOCIAL_STUDIES("social studies"),
    
    LANGUAGE("language"),
    
    HOMEROOM_ADVISORY("homeroom/advisory"),
    
    INTERVENTIONS_ONLINE_LEARNING("interventions/online learning"),
    
    TECHNOLOGY_AND_ENGINEERING("technology and engineering"),
    
    PE_AND_HEALTH("PE and health"),
    
    ARTS_AND_MUSIC("arts and music"),
    
    OTHER("other"),
    
    EMPTY("");

    private String value;

    SubjectEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static SubjectEnum fromValue(String value) {
      for (SubjectEnum b : SubjectEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<SubjectEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final SubjectEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public SubjectEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return SubjectEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_SUBJECT = "subject";
  @SerializedName(SERIALIZED_NAME_SUBJECT)
  private SubjectEnum subject;

  public static final String SERIALIZED_NAME_TEACHER = "teacher";
  @SerializedName(SERIALIZED_NAME_TEACHER)
  private String teacher;

  public static final String SERIALIZED_NAME_TEACHERS = "teachers";
  @SerializedName(SERIALIZED_NAME_TEACHERS)
  private List<String> teachers = null;

  public static final String SERIALIZED_NAME_TERM_ID = "term_id";
  @SerializedName(SERIALIZED_NAME_TERM_ID)
  private String termId;

  public Section() {
  }

  public Section course(String course) {
    
    
    
    
    this.course = course;
    return this;
  }

   /**
   * Get course
   * @return course
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getCourse() {
    return course;
  }


  public void setCourse(String course) {
    
    
    
    this.course = course;
  }


  public Section created(String created) {
    
    
    
    
    this.created = created;
    return this;
  }

   /**
   * Get created
   * @return created
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getCreated() {
    return created;
  }


  public void setCreated(String created) {
    
    
    
    this.created = created;
  }


  public Section district(String district) {
    
    
    
    
    this.district = district;
    return this;
  }

   /**
   * Get district
   * @return district
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getDistrict() {
    return district;
  }


  public void setDistrict(String district) {
    
    
    
    this.district = district;
  }


  public Section ext(Object ext) {
    
    
    
    
    this.ext = ext;
    return this;
  }

   /**
   * Get ext
   * @return ext
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getExt() {
    return ext;
  }


  public void setExt(Object ext) {
    
    
    
    this.ext = ext;
  }


  public Section grade(GradeEnum grade) {
    
    
    
    
    this.grade = grade;
    return this;
  }

   /**
   * Get grade
   * @return grade
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public GradeEnum getGrade() {
    return grade;
  }


  public void setGrade(GradeEnum grade) {
    
    
    
    this.grade = grade;
  }


  public Section id(String id) {
    
    
    
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getId() {
    return id;
  }


  public void setId(String id) {
    
    
    
    this.id = id;
  }


  public Section lastModified(String lastModified) {
    
    
    
    
    this.lastModified = lastModified;
    return this;
  }

   /**
   * Get lastModified
   * @return lastModified
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getLastModified() {
    return lastModified;
  }


  public void setLastModified(String lastModified) {
    
    
    
    this.lastModified = lastModified;
  }


  public Section name(String name) {
    
    
    
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    
    
    
    this.name = name;
  }


  public Section period(String period) {
    
    
    
    
    this.period = period;
    return this;
  }

   /**
   * Get period
   * @return period
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getPeriod() {
    return period;
  }


  public void setPeriod(String period) {
    
    
    
    this.period = period;
  }


  public Section school(String school) {
    
    
    
    
    this.school = school;
    return this;
  }

   /**
   * Get school
   * @return school
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getSchool() {
    return school;
  }


  public void setSchool(String school) {
    
    
    
    this.school = school;
  }


  public Section sectionNumber(String sectionNumber) {
    
    
    
    
    this.sectionNumber = sectionNumber;
    return this;
  }

   /**
   * Get sectionNumber
   * @return sectionNumber
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getSectionNumber() {
    return sectionNumber;
  }


  public void setSectionNumber(String sectionNumber) {
    
    
    
    this.sectionNumber = sectionNumber;
  }


  public Section sisId(String sisId) {
    
    
    
    
    this.sisId = sisId;
    return this;
  }

   /**
   * Get sisId
   * @return sisId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getSisId() {
    return sisId;
  }


  public void setSisId(String sisId) {
    
    
    
    this.sisId = sisId;
  }


  public Section students(List<String> students) {
    
    
    
    
    this.students = students;
    return this;
  }

  public Section addStudentsItem(String studentsItem) {
    if (this.students == null) {
      this.students = new ArrayList<>();
    }
    this.students.add(studentsItem);
    return this;
  }

   /**
   * Get students
   * @return students
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getStudents() {
    return students;
  }


  public void setStudents(List<String> students) {
    
    
    
    this.students = students;
  }


  public Section subject(SubjectEnum subject) {
    
    
    
    
    this.subject = subject;
    return this;
  }

   /**
   * Get subject
   * @return subject
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public SubjectEnum getSubject() {
    return subject;
  }


  public void setSubject(SubjectEnum subject) {
    
    
    
    this.subject = subject;
  }


  public Section teacher(String teacher) {
    
    
    
    
    this.teacher = teacher;
    return this;
  }

   /**
   * Get teacher
   * @return teacher
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getTeacher() {
    return teacher;
  }


  public void setTeacher(String teacher) {
    
    
    
    this.teacher = teacher;
  }


  public Section teachers(List<String> teachers) {
    
    
    
    
    this.teachers = teachers;
    return this;
  }

  public Section addTeachersItem(String teachersItem) {
    if (this.teachers == null) {
      this.teachers = new ArrayList<>();
    }
    this.teachers.add(teachersItem);
    return this;
  }

   /**
   * Get teachers
   * @return teachers
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getTeachers() {
    return teachers;
  }


  public void setTeachers(List<String> teachers) {
    
    
    
    this.teachers = teachers;
  }


  public Section termId(String termId) {
    
    
    
    
    this.termId = termId;
    return this;
  }

   /**
   * Get termId
   * @return termId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getTermId() {
    return termId;
  }


  public void setTermId(String termId) {
    
    
    
    this.termId = termId;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the Section instance itself
   */
  public Section putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Section section = (Section) o;
    return Objects.equals(this.course, section.course) &&
        Objects.equals(this.created, section.created) &&
        Objects.equals(this.district, section.district) &&
        Objects.equals(this.ext, section.ext) &&
        Objects.equals(this.grade, section.grade) &&
        Objects.equals(this.id, section.id) &&
        Objects.equals(this.lastModified, section.lastModified) &&
        Objects.equals(this.name, section.name) &&
        Objects.equals(this.period, section.period) &&
        Objects.equals(this.school, section.school) &&
        Objects.equals(this.sectionNumber, section.sectionNumber) &&
        Objects.equals(this.sisId, section.sisId) &&
        Objects.equals(this.students, section.students) &&
        Objects.equals(this.subject, section.subject) &&
        Objects.equals(this.teacher, section.teacher) &&
        Objects.equals(this.teachers, section.teachers) &&
        Objects.equals(this.termId, section.termId)&&
        Objects.equals(this.additionalProperties, section.additionalProperties);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(course, created, district, ext, grade, id, lastModified, name, period, school, sectionNumber, sisId, students, subject, teacher, teachers, termId, additionalProperties);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Section {\n");
    sb.append("    course: ").append(toIndentedString(course)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    district: ").append(toIndentedString(district)).append("\n");
    sb.append("    ext: ").append(toIndentedString(ext)).append("\n");
    sb.append("    grade: ").append(toIndentedString(grade)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    lastModified: ").append(toIndentedString(lastModified)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    period: ").append(toIndentedString(period)).append("\n");
    sb.append("    school: ").append(toIndentedString(school)).append("\n");
    sb.append("    sectionNumber: ").append(toIndentedString(sectionNumber)).append("\n");
    sb.append("    sisId: ").append(toIndentedString(sisId)).append("\n");
    sb.append("    students: ").append(toIndentedString(students)).append("\n");
    sb.append("    subject: ").append(toIndentedString(subject)).append("\n");
    sb.append("    teacher: ").append(toIndentedString(teacher)).append("\n");
    sb.append("    teachers: ").append(toIndentedString(teachers)).append("\n");
    sb.append("    termId: ").append(toIndentedString(termId)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("course");
    openapiFields.add("created");
    openapiFields.add("district");
    openapiFields.add("ext");
    openapiFields.add("grade");
    openapiFields.add("id");
    openapiFields.add("last_modified");
    openapiFields.add("name");
    openapiFields.add("period");
    openapiFields.add("school");
    openapiFields.add("section_number");
    openapiFields.add("sis_id");
    openapiFields.add("students");
    openapiFields.add("subject");
    openapiFields.add("teacher");
    openapiFields.add("teachers");
    openapiFields.add("term_id");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to Section
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!Section.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in Section is not found in the empty JSON string", Section.openapiRequiredFields.toString()));
        }
      }
      if (!jsonObj.get("course").isJsonNull() && (jsonObj.get("course") != null && !jsonObj.get("course").isJsonNull()) && !jsonObj.get("course").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `course` to be a primitive type in the JSON string but got `%s`", jsonObj.get("course").toString()));
      }
      if ((jsonObj.get("created") != null && !jsonObj.get("created").isJsonNull()) && !jsonObj.get("created").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `created` to be a primitive type in the JSON string but got `%s`", jsonObj.get("created").toString()));
      }
      if ((jsonObj.get("district") != null && !jsonObj.get("district").isJsonNull()) && !jsonObj.get("district").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `district` to be a primitive type in the JSON string but got `%s`", jsonObj.get("district").toString()));
      }
      if (!jsonObj.get("grade").isJsonNull() && (jsonObj.get("grade") != null && !jsonObj.get("grade").isJsonNull()) && !jsonObj.get("grade").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `grade` to be a primitive type in the JSON string but got `%s`", jsonObj.get("grade").toString()));
      }
      if ((jsonObj.get("id") != null && !jsonObj.get("id").isJsonNull()) && !jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if ((jsonObj.get("last_modified") != null && !jsonObj.get("last_modified").isJsonNull()) && !jsonObj.get("last_modified").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `last_modified` to be a primitive type in the JSON string but got `%s`", jsonObj.get("last_modified").toString()));
      }
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if (!jsonObj.get("period").isJsonNull() && (jsonObj.get("period") != null && !jsonObj.get("period").isJsonNull()) && !jsonObj.get("period").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `period` to be a primitive type in the JSON string but got `%s`", jsonObj.get("period").toString()));
      }
      if ((jsonObj.get("school") != null && !jsonObj.get("school").isJsonNull()) && !jsonObj.get("school").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `school` to be a primitive type in the JSON string but got `%s`", jsonObj.get("school").toString()));
      }
      if (!jsonObj.get("section_number").isJsonNull() && (jsonObj.get("section_number") != null && !jsonObj.get("section_number").isJsonNull()) && !jsonObj.get("section_number").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `section_number` to be a primitive type in the JSON string but got `%s`", jsonObj.get("section_number").toString()));
      }
      if ((jsonObj.get("sis_id") != null && !jsonObj.get("sis_id").isJsonNull()) && !jsonObj.get("sis_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `sis_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("sis_id").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("students") != null && !jsonObj.get("students").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `students` to be an array in the JSON string but got `%s`", jsonObj.get("students").toString()));
      }
      if (!jsonObj.get("subject").isJsonNull() && (jsonObj.get("subject") != null && !jsonObj.get("subject").isJsonNull()) && !jsonObj.get("subject").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `subject` to be a primitive type in the JSON string but got `%s`", jsonObj.get("subject").toString()));
      }
      if (!jsonObj.get("teacher").isJsonNull() && (jsonObj.get("teacher") != null && !jsonObj.get("teacher").isJsonNull()) && !jsonObj.get("teacher").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `teacher` to be a primitive type in the JSON string but got `%s`", jsonObj.get("teacher").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("teachers") != null && !jsonObj.get("teachers").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `teachers` to be an array in the JSON string but got `%s`", jsonObj.get("teachers").toString()));
      }
      if (!jsonObj.get("term_id").isJsonNull() && (jsonObj.get("term_id") != null && !jsonObj.get("term_id").isJsonNull()) && !jsonObj.get("term_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `term_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("term_id").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Section.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Section' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Section> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Section.class));

       return (TypeAdapter<T>) new TypeAdapter<Section>() {
           @Override
           public void write(JsonWriter out, Section value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public Section read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             Section instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of Section given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of Section
  * @throws IOException if the JSON string is invalid with respect to Section
  */
  public static Section fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Section.class);
  }

 /**
  * Convert an instance of Section to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

