/*
 * Data API
 * Serves the Clever Data API
 *
 * The version of the OpenAPI document: 3.1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.CourseResponse;
import com.konfigthis.client.model.CoursesResponse;
import com.konfigthis.client.model.DistrictResponse;
import com.konfigthis.client.model.ResourcesResponse;
import com.konfigthis.client.model.SchoolsResponse;
import com.konfigthis.client.model.SectionsResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CoursesApi
 */
@Disabled
public class CoursesApiTest {

    private static CoursesApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new CoursesApi(apiClient);
    }

    /**
     * Returns the district for a course
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getDistrictTest() throws ApiException {
        String id = null;
        DistrictResponse response = api.getDistrict(id)
                .execute();
        // TODO: test validations
    }

    /**
     * Returns a list of courses
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getListTest() throws ApiException {
        Integer limit = null;
        String startingAfter = null;
        String endingBefore = null;
        String count = null;
        CoursesResponse response = api.getList()
                .limit(limit)
                .startingAfter(startingAfter)
                .endingBefore(endingBefore)
                .count(count)
                .execute();
        // TODO: test validations
    }

    /**
     * Returns the resources for a course
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getResourcesTest() throws ApiException {
        String id = null;
        Integer limit = null;
        String startingAfter = null;
        String endingBefore = null;
        ResourcesResponse response = api.getResources(id)
                .limit(limit)
                .startingAfter(startingAfter)
                .endingBefore(endingBefore)
                .execute();
        // TODO: test validations
    }

    /**
     * Returns the schools for a course
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getSchoolsTest() throws ApiException {
        String id = null;
        Integer limit = null;
        String startingAfter = null;
        String endingBefore = null;
        SchoolsResponse response = api.getSchools(id)
                .limit(limit)
                .startingAfter(startingAfter)
                .endingBefore(endingBefore)
                .execute();
        // TODO: test validations
    }

    /**
     * Returns the sections for a course
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getSectionsTest() throws ApiException {
        String id = null;
        Integer limit = null;
        String startingAfter = null;
        String endingBefore = null;
        SectionsResponse response = api.getSections(id)
                .limit(limit)
                .startingAfter(startingAfter)
                .endingBefore(endingBefore)
                .execute();
        // TODO: test validations
    }

    /**
     * Returns a specific course
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getSpecificCourseTest() throws ApiException {
        String id = null;
        CourseResponse response = api.getSpecificCourse(id)
                .execute();
        // TODO: test validations
    }

}
