/*
 * Data API
 * Serves the Clever Data API
 *
 * The version of the OpenAPI document: 3.1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.CourseResponse;
import com.konfigthis.client.model.DistrictResponse;
import com.konfigthis.client.model.ResourcesResponse;
import com.konfigthis.client.model.SchoolResponse;
import com.konfigthis.client.model.SectionResponse;
import com.konfigthis.client.model.SectionsResponse;
import com.konfigthis.client.model.TermResponse;
import com.konfigthis.client.model.UsersResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SectionsApi
 */
@Disabled
public class SectionsApiTest {

    private static SectionsApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new SectionsApi(apiClient);
    }

    /**
     * Returns the course for a section
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getCourseTest() throws ApiException {
        String id = null;
        CourseResponse response = api.getCourse(id)
                .execute();
        // TODO: test validations
    }

    /**
     * Returns the district for a section
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getDistrictTest() throws ApiException {
        String id = null;
        DistrictResponse response = api.getDistrict(id)
                .execute();
        // TODO: test validations
    }

    /**
     * Returns a list of sections
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getListTest() throws ApiException {
        Integer limit = null;
        String startingAfter = null;
        String endingBefore = null;
        String count = null;
        SectionsResponse response = api.getList()
                .limit(limit)
                .startingAfter(startingAfter)
                .endingBefore(endingBefore)
                .count(count)
                .execute();
        // TODO: test validations
    }

    /**
     * Returns the resources for a section
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getResourcesTest() throws ApiException {
        String id = null;
        Integer limit = null;
        String startingAfter = null;
        String endingBefore = null;
        ResourcesResponse response = api.getResources(id)
                .limit(limit)
                .startingAfter(startingAfter)
                .endingBefore(endingBefore)
                .execute();
        // TODO: test validations
    }

    /**
     * Returns the school for a section
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getSchoolTest() throws ApiException {
        String id = null;
        SchoolResponse response = api.getSchool(id)
                .execute();
        // TODO: test validations
    }

    /**
     * Returns a specific section
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getSpecificSectionTest() throws ApiException {
        String id = null;
        SectionResponse response = api.getSpecificSection(id)
                .execute();
        // TODO: test validations
    }

    /**
     * Returns the term for a section
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getTermTest() throws ApiException {
        String id = null;
        TermResponse response = api.getTerm(id)
                .execute();
        // TODO: test validations
    }

    /**
     * Returns the student and/or teacher users for a section
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getUsersTest() throws ApiException {
        String id = null;
        String role = null;
        Integer limit = null;
        String startingAfter = null;
        String endingBefore = null;
        UsersResponse response = api.getUsers(id)
                .role(role)
                .limit(limit)
                .startingAfter(startingAfter)
                .endingBefore(endingBefore)
                .execute();
        // TODO: test validations
    }

}
