/*
 * Data API
 * Serves the Clever Data API
 *
 * The version of the OpenAPI document: 3.1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.DistrictResponse;
import com.konfigthis.client.model.ResourcesResponse;
import com.konfigthis.client.model.SchoolsResponse;
import com.konfigthis.client.model.SectionsResponse;
import com.konfigthis.client.model.UserResponse;
import com.konfigthis.client.model.UsersResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UsersApi
 */
@Disabled
public class UsersApiTest {

    private static UsersApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new UsersApi(apiClient);
    }

    /**
     * Returns the district for a user
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getDistrictTest() throws ApiException {
        String id = null;
        DistrictResponse response = api.getDistrict(id)
                .execute();
        // TODO: test validations
    }

    /**
     * Returns a list of contact, district admin, staff, student, and/or teacher users
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getListTest() throws ApiException {
        Integer limit = null;
        String role = null;
        String startingAfter = null;
        String endingBefore = null;
        String count = null;
        UsersResponse response = api.getList()
                .limit(limit)
                .role(role)
                .startingAfter(startingAfter)
                .endingBefore(endingBefore)
                .count(count)
                .execute();
        // TODO: test validations
    }

    /**
     * Returns the contact users for a student user
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getMyContactsTest() throws ApiException {
        String id = null;
        Integer limit = null;
        String startingAfter = null;
        String endingBefore = null;
        UsersResponse response = api.getMyContacts(id)
                .limit(limit)
                .startingAfter(startingAfter)
                .endingBefore(endingBefore)
                .execute();
        // TODO: test validations
    }

    /**
     * Returns the resources for a user
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getResourcesTest() throws ApiException {
        String id = null;
        Integer limit = null;
        String startingAfter = null;
        String endingBefore = null;
        ResourcesResponse response = api.getResources(id)
                .limit(limit)
                .startingAfter(startingAfter)
                .endingBefore(endingBefore)
                .execute();
        // TODO: test validations
    }

    /**
     * Returns the schools for a user
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getSchoolsTest() throws ApiException {
        String id = null;
        String primary = null;
        Integer limit = null;
        String startingAfter = null;
        String endingBefore = null;
        SchoolsResponse response = api.getSchools(id)
                .primary(primary)
                .limit(limit)
                .startingAfter(startingAfter)
                .endingBefore(endingBefore)
                .execute();
        // TODO: test validations
    }

    /**
     * Returns the sections for a user
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getSectionsTest() throws ApiException {
        String id = null;
        Integer limit = null;
        String startingAfter = null;
        String endingBefore = null;
        SectionsResponse response = api.getSections(id)
                .limit(limit)
                .startingAfter(startingAfter)
                .endingBefore(endingBefore)
                .execute();
        // TODO: test validations
    }

    /**
     * Returns the student users for a teacher or contact user
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getStudentUsersTest() throws ApiException {
        String id = null;
        Integer limit = null;
        String startingAfter = null;
        String endingBefore = null;
        UsersResponse response = api.getStudentUsers(id)
                .limit(limit)
                .startingAfter(startingAfter)
                .endingBefore(endingBefore)
                .execute();
        // TODO: test validations
    }

    /**
     * Returns the teacher users for a student user
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getTeachersForUserTest() throws ApiException {
        String id = null;
        Integer limit = null;
        String startingAfter = null;
        String endingBefore = null;
        UsersResponse response = api.getTeachersForUser(id)
                .limit(limit)
                .startingAfter(startingAfter)
                .endingBefore(endingBefore)
                .execute();
        // TODO: test validations
    }

    /**
     * Returns a specific user
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getUserByIdTest() throws ApiException {
        String id = null;
        UserResponse response = api.getUserById(id)
                .execute();
        // TODO: test validations
    }

}
